-- local ok, lspconfig = pcall(require, "lspconfig")
-- if not ok then
--   return
-- end
--
-- require("mason-lspconfig").setup_handlers({
--   function(server_name)
--     lspconfig[server_name].setup({})
--   end,
--   ["sumneko_lua"] = function()
--     lspconfig.sumneko_lua.setup(require("lua-dev").setup({
--       settings = {
--         Lua = {
--           format = {
--             enable = false,
--           },
--           hint = {
--             enable = true,
--             arrayIndex = "Disable", -- "Enable", "Auto", "Disable"
--             await = true,
--             paramName = "Disable", -- "All", "Literal", "Disable"
--             paramType = false,
--             semicolon = "Disable", -- "All", "SameLine", "Disable"
--             setType = true,
--           },
--           diagnostics = {
--             globals = { "P" },
--           },
--         },
--       },
--     }))
--   end,
-- })
