mo.style = {
  icons = {
    git = {
      added = "",
      modified = "",
      deleted = "",
      renamed = "",
      ignored = "",
      untracked = "",
      unstaged = "",
      megred = "",
      staged = "",
      conflict = "",
      branch = "",
    },
    dap = {
      breakpoint = "",
      stopped = "",
      pause = "",
      play = "",
      step_into = "",
      step_over = "",
      step_out = "",
      step_back = "",
      rerun = "",
      stop = "",
    },
    diagnostics = {
      error = "",
      warn = "",
      info = "",
      hint = "",
    },
    documents = {
      collapsed = "",
      expanded = "",
      file = "",
      files = "",
      file_symlink = "",
      folder = "",
      folder_open = "",
      folder_symlink = "",
      empty_folder = "",
      empty_folder_open = "",
    },
    misc = {
      lsp = "",
      treesitter = "",
      telescope = "",
      selection = "",
      creation = "",
      search = "",
      history = "",
      vim = "",
      exit = "",
      ellipsis = "…",
      electron = "",
      bookmark = "",
      target = "",
      snow = "",
      cloud = "",
      circle = "",
      progress = {
        "██",
        "▇▇",
        "▆▆",
        "▅▅",
        "▄▄",
        "▃▃",
        "▂▂",
        "▁▁",
        "  ",
      },
    },
    lsp = {
      kinds = {
        class = "",
        color = "",
        constant = "",
        constructor = "",
        enum = "",
        enumMember = "",
        event = "",
        field = "",
        file = "",
        folder = "",
        ["function"] = "",
        interface = "",
        keyword = "",
        method = "",
        module = "",
        operator = "",
        property = "",
        reference = "",
        snippet = "",
        struct = "",
        text = "",
        typeParameter = "",
        unit = "",
        value = "",
        variable = "",
        namespace = "?",
        package = "?",
        string = "?",
        number = "?",
        boolean = "?",
        array = "?",
        object = "?",
        key = "?",
        null = "?",
      },
    },
  },
}
